# Generated by Django 3.0 on 2019-12-29 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('events', '0002_servicesinevents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServicesInEvents',
            new_name='ServicesInEvent',
        ),
    ]
