# Generated by Django 3.0 on 2019-12-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('min_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
