# Generated by Django 3.0 on 2019-12-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CLients',
            new_name='Client',
        ),
    ]
